import type { Movie, MovieCollection } from "../types/api";

export const DEMO_MOVIES: Movie[] = [
  {
    id: "kaithi-2019",
    title: "Kaithi",
    originalTitle: "கைதி",
    releaseYear: 2019,
    runtimeMinutes: 146,
    certificate: "U/A",
    overview:
      "A recently released prisoner must drive poisoned police officers to safety through the night while criminals close in—and every mile brings him closer to the daughter he has never met.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/7/79/Kaithi_2019_poster.jpg",
    genres: ["Action", "Thriller"],
    themes: ["One night", "Prisoner", "Chase", "Fatherhood"],
    director: "Lokesh Kanagaraj",
    cast: ["Karthi", "Narain", "Arjun Das"],
    prominenceScore: 0.82,
    qualityScore: 0.97,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Kaithi_(2019_film)",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "jai-bhim-2021",
    title: "Jai Bhim",
    originalTitle: "ஜெய் பீம்",
    releaseYear: 2021,
    runtimeMinutes: 164,
    certificate: "A",
    overview:
      "After a tribal man disappears in police custody, his wife seeks the help of a principled lawyer to expose institutional violence and bring him home.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/a/ad/Jai_Bhim_film_poster.jpg",
    genres: ["Legal drama", "Mystery"],
    themes: ["Courtroom", "Injustice", "Civil rights", "Resistance"],
    director: "T. J. Gnanavel",
    cast: ["Suriya", "Lijomol Jose", "Manikandan"],
    prominenceScore: 0.61,
    qualityScore: 0.98,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Jai_Bhim_(film)",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "aruvi-2017",
    title: "Aruvi",
    originalTitle: "அருவி",
    releaseYear: 2017,
    runtimeMinutes: 130,
    certificate: "U/A",
    overview:
      "A young woman pushed to society’s margins turns a television studio into the stage for a fierce, darkly funny reckoning with consumerism and prejudice.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/f/f0/Aruvi_poster.jpg",
    genres: ["Drama", "Satire"],
    themes: ["Outsider", "Social justice", "Media", "Rebellion"],
    director: "Arun Prabhu Purushothaman",
    cast: ["Aditi Balan", "Lakshmi Gopalaswamy"],
    prominenceScore: 0.06,
    qualityScore: 0.96,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Aruvi",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "96-2018",
    title: "’96",
    originalTitle: "96",
    releaseYear: 2018,
    runtimeMinutes: 158,
    certificate: "U",
    overview:
      "Two former school sweethearts meet at a reunion after twenty-two years and spend one tender night confronting memory, distance, and the life they might have shared.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/c/c4/%2796_film_poster.jpg",
    genres: ["Romance", "Drama"],
    themes: ["Reunion", "Nostalgia", "Unrequited love", "School"],
    director: "C. Prem Kumar",
    cast: ["Vijay Sethupathi", "Trisha Krishnan"],
    prominenceScore: 0.97,
    qualityScore: 0.97,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/%2796_(film)",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "pariyerum-perumal-2018",
    title: "Pariyerum Perumal",
    originalTitle: "பரியேறும் பெருமாள்",
    releaseYear: 2018,
    runtimeMinutes: 154,
    certificate: "U/A",
    overview:
      "An idealistic law student forms a friendship across caste lines and is forced to face the quiet humiliations and brutal violence built into the world around him.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/3/35/Pariyerum_Perumal.jpg",
    genres: ["Drama", "Romance"],
    themes: ["Caste", "Education", "Social justice", "Coming of age"],
    director: "Mari Selvaraj",
    cast: ["Kathir", "Anandhi", "Yogi Babu"],
    prominenceScore: 0.41,
    qualityScore: 0.98,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Pariyerum_Perumal",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "super-deluxe-2019",
    title: "Super Deluxe",
    originalTitle: "சூப்பர் டீலக்ஸ்",
    releaseYear: 2019,
    runtimeMinutes: 176,
    certificate: "A",
    overview:
      "Four interlocking stories collide over one strange day, following people caught between shame, desire, faith, and chance in a wickedly inventive dark comedy.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/a/a1/Super_Deluxe_film_poster.jpg",
    genres: ["Drama", "Dark comedy"],
    themes: ["Hyperlink narrative", "Identity", "Fate", "Family"],
    director: "Thiagarajan Kumararaja",
    cast: [
      "Vijay Sethupathi",
      "Fahadh Faasil",
      "Samantha Ruth Prabhu",
      "Ramya Krishnan",
    ],
    prominenceScore: 0.98,
    qualityScore: 0.98,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Super_Deluxe_(film)",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "vikram-vedha-2017",
    title: "Vikram Vedha",
    originalTitle: "விக்ரம் வேதா",
    releaseYear: 2017,
    runtimeMinutes: 147,
    certificate: "U/A",
    overview:
      "A relentless police officer hunts a charismatic gangster, only to have three morally tangled stories unsettle everything he believes about good and evil.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/0/03/Vikram_Vedha_poster.jpg",
    genres: ["Crime", "Thriller"],
    themes: ["Moral ambiguity", "Police", "Gangster", "Folklore"],
    director: "Pushkar–Gayathri",
    cast: ["R. Madhavan", "Vijay Sethupathi", "Shraddha Srinath"],
    prominenceScore: 0.92,
    qualityScore: 0.97,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Vikram_Vedha",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "kadaisi-vivasayi-2022",
    title: "Kadaisi Vivasayi",
    originalTitle: "கடைசி விவசாயி",
    releaseYear: 2022,
    runtimeMinutes: 145,
    certificate: "U",
    overview:
      "An elderly farmer who tends the last green patch in his village is pulled into an absurd legal case, while the land and rituals around him quietly endure.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/0/09/Kadaisi_Vivasayi.jpg",
    genres: ["Drama", "Comedy"],
    themes: ["Village", "Farming", "Tradition", "Nature"],
    director: "M. Manikandan",
    cast: ["Nallandi", "Vijay Sethupathi", "Yogi Babu"],
    prominenceScore: 0.18,
    qualityScore: 0.96,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Kadaisi_Vivasayi",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "maaveeran-2023",
    title: "Maaveeran",
    originalTitle: "மாவீரன்",
    releaseYear: 2023,
    runtimeMinutes: 166,
    certificate: "U/A",
    overview:
      "A timid comic-strip artist begins hearing a narrator who predicts danger, pushing him toward the courage needed to protect his housing community from corruption.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/5/55/Maaveeran_2023_poster.jpg",
    genres: ["Action", "Comedy", "Fantasy"],
    themes: ["Political satire", "Courage", "Voice", "Community"],
    director: "Madonne Ashwin",
    cast: ["Sivakarthikeyan", "Aditi Shankar", "Mysskin", "Saritha"],
    prominenceScore: 0.43,
    qualityScore: 0.94,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Maaveeran_(2023_film)",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "por-thozhil-2023",
    title: "Por Thozhil",
    originalTitle: "போர் தொழில்",
    releaseYear: 2023,
    runtimeMinutes: 147,
    certificate: "U/A",
    overview:
      "A nervous young officer and a closed-off veteran follow a trail of ritualistic murders, testing their uneasy partnership against a methodical killer.",
    language: "Tamil",
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/5/58/Por_Thozhil.jpg",
    genres: ["Crime", "Thriller"],
    themes: ["Serial killer", "Investigation", "Mentorship", "Police"],
    director: "Vignesh Raja",
    cast: ["R. Sarathkumar", "Ashok Selvan", "Nikhila Vimal"],
    prominenceScore: 0.66,
    qualityScore: 0.95,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Por_Thozhil",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "sarpatta-parambarai-2021",
    title: "Sarpatta Parambarai",
    originalTitle: "சார்பட்டா பரம்பரை",
    releaseYear: 2021,
    runtimeMinutes: 173,
    certificate: "U/A",
    overview:
      "In 1970s North Chennai, a laborer gets one chance to restore his boxing clan’s honor, but politics, pride, and addiction make the hardest fight his own.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/a/a6/Sarpatta_Parambarai.jpg",
    genres: ["Sports", "Drama"],
    themes: ["Boxing", "North Chennai", "Politics", "Redemption"],
    director: "Pa. Ranjith",
    cast: ["Arya", "Pasupathy", "Dushara Vijayan", "Shabeer Kallarakkal"],
    prominenceScore: 0.69,
    qualityScore: 0.97,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Sarpatta_Parambarai",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
  {
    id: "kuttrame-thandanai-2016",
    title: "Kuttrame Thandanai",
    originalTitle: "குற்றமே தண்டனை",
    releaseYear: 2016,
    runtimeMinutes: 100,
    certificate: "U/A",
    overview:
      "A man gradually losing his peripheral vision witnesses a murder and faces a choice between justice and the money that could save his sight.",
    language: "Tamil",
    posterUrl:
      "https://upload.wikimedia.org/wikipedia/en/8/8e/Kuttrame_Thandanai.jpg",
    genres: ["Crime", "Drama"],
    themes: ["Moral dilemma", "Witness", "Disability", "Neo-noir"],
    director: "M. Manikandan",
    cast: ["Vidharth", "Pooja Devariya", "Aishwarya Rajesh"],
    prominenceScore: 0.12,
    qualityScore: 0.93,
    dataQualityStatus: "verified",
    sourceUrl: "https://en.wikipedia.org/wiki/Kuttrame_Thandanai",
    sourceUpdatedAt: "2026-08-20T00:00:00Z",
  },
];

export const GENRE_OPTIONS = [
  "Action",
  "Comedy",
  "Crime",
  "Drama",
  "Fantasy",
  "Legal drama",
  "Romance",
  "Sports",
  "Thriller",
] as const;

export const THEME_OPTIONS = [
  "Courtroom",
  "Family",
  "Hidden gem",
  "Investigation",
  "One night",
  "Political satire",
  "Social justice",
  "Village",
] as const;

export const DEMO_SHARED_COLLECTION: MovieCollection = {
  id: "voices-of-change",
  ownerDisplayName: "TamilTrove curators",
  name: "Voices of change",
  description:
    "Tamil films that turn resistance, dignity, and difficult questions into unforgettable cinema.",
  visibility: "public",
  shareToken: "voices-of-change",
  items: [
    "jai-bhim-2021",
    "pariyerum-perumal-2018",
    "aruvi-2017",
    "maaveeran-2023",
  ].map((movieId, position) => ({
    movieId,
    position,
    movie: DEMO_MOVIES.find((movie) => movie.id === movieId),
  })),
};

export function getDemoMovie(id: string): Movie | undefined {
  return DEMO_MOVIES.find((movie) => movie.id === id);
}
